# Generated by Django 5.0.4 on 2026-04-02 14:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'boards',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_type', models.CharField(choices=[('human', 'Human'), ('agent', 'Agent')], default='human', max_length=10)),
                ('agent_type', models.CharField(blank=True, max_length=10)),
                ('body', models.TextField()),
                ('is_question', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('source_channel', models.CharField(choices=[('in_app', 'In-App'), ('slack', 'Slack'), ('email', 'Email')], default='in_app', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6366F1', max_length=7)),
            ],
            options={
                'db_table': 'labels',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('color', models.CharField(default='#6366F1', max_length=7)),
                ('ticket_prefix', models.CharField(default='AD', max_length=10)),
                ('ticket_counter', models.IntegerField(default=0)),
                ('default_target_branch', models.CharField(default='main', max_length=255)),
                ('branch_naming_template', models.CharField(default='feature/{prefix}-{ticket_id}-{slug}', max_length=255)),
                ('pr_title_template', models.CharField(default='[{prefix}-{ticket_id}] {ticket_title}', max_length=255)),
                ('agent_custom_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_memberships',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_key', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('acceptance_criteria', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='none', max_length=10)),
                ('position', models.IntegerField(default=0)),
                ('challenge_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('waiting_for_input', 'Waiting For Input'), ('approved', 'Approved'), ('generated', 'Generated'), ('rejected', 'Rejected'), ('pr_created', 'Pr Created'), ('pr_merged', 'Pr Merged'), ('changes_requested', 'Changes Requested'), ('fixed', 'Fixed'), ('failed', 'Failed')], default='not_started', max_length=20)),
                ('plan_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('waiting_for_input', 'Waiting For Input'), ('approved', 'Approved'), ('generated', 'Generated'), ('rejected', 'Rejected'), ('pr_created', 'Pr Created'), ('pr_merged', 'Pr Merged'), ('changes_requested', 'Changes Requested'), ('fixed', 'Fixed'), ('failed', 'Failed')], default='not_started', max_length=20)),
                ('code_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('waiting_for_input', 'Waiting For Input'), ('approved', 'Approved'), ('generated', 'Generated'), ('rejected', 'Rejected'), ('pr_created', 'Pr Created'), ('pr_merged', 'Pr Merged'), ('changes_requested', 'Changes Requested'), ('fixed', 'Fixed'), ('failed', 'Failed')], default='not_started', max_length=20)),
                ('review_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('waiting_for_input', 'Waiting For Input'), ('approved', 'Approved'), ('generated', 'Generated'), ('rejected', 'Rejected'), ('pr_created', 'Pr Created'), ('pr_merged', 'Pr Merged'), ('changes_requested', 'Changes Requested'), ('fixed', 'Fixed'), ('failed', 'Failed')], default='not_started', max_length=20)),
                ('fix_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('waiting_for_input', 'Waiting For Input'), ('approved', 'Approved'), ('generated', 'Generated'), ('rejected', 'Rejected'), ('pr_created', 'Pr Created'), ('pr_merged', 'Pr Merged'), ('changes_requested', 'Changes Requested'), ('fixed', 'Fixed'), ('failed', 'Failed')], default='not_started', max_length=20)),
                ('estimated_complexity', models.CharField(blank=True, choices=[('xs', 'Xs'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'Xl')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.IntegerField(default=0)),
                ('color', models.CharField(default='#E5E7EB', max_length=7)),
                ('wip_limit', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='projects.board')),
            ],
            options={
                'db_table': 'columns',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ColumnAgentTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('challenge', 'Challenge'), ('plan', 'Plan'), ('code', 'Code'), ('review', 'Review'), ('fix', 'Fix')], max_length=10)),
                ('trigger_mode', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('position', models.IntegerField(default=0)),
                ('condition_challenge_approved', models.BooleanField(default=False)),
                ('condition_plan_approved', models.BooleanField(default=False)),
                ('condition_has_repos', models.BooleanField(default=False)),
                ('condition_pr_created', models.BooleanField(default=False)),
                ('condition_review_done', models.BooleanField(default=False)),
                ('notify_on_start', models.BooleanField(default=False)),
                ('notify_on_complete', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_move_on_complete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.column')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='projects.column')),
            ],
            options={
                'db_table': 'column_agent_triggers',
                'ordering': ['position'],
            },
        ),
    ]
