# Generated by Django 5.1.15 on 2026-04-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='agent_challenge_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='agent_code_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='agent_fix_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='agent_global_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='agent_plan_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='agent_review_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='challenge_auto_approve_threshold',
            field=models.IntegerField(default=85),
        ),
        migrations.AddField(
            model_name='project',
            name='fix_max_iterations',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='project',
            name='fix_severity_filter',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='llm_model',
            field=models.CharField(choices=[('claude-sonnet-4-20250514', 'Claude Sonnet 4'), ('claude-opus-4-20250514', 'Claude Opus 4')], default='claude-sonnet-4-20250514', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='notification_channel_override',
            field=models.CharField(blank=True, choices=[('in_app', 'In-App'), ('slack', 'Slack'), ('email', 'Email')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='notify_agent_questions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='notify_fix_applied',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='notify_plan_generated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='notify_pr_created',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='notify_review_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pr_body_template',
            field=models.TextField(blank=True, default='## Ticket\n{ticket_title}\n\n## Description\n{ticket_description}\n\n## Plan\n{plan_summary}'),
        ),
    ]
