# Generated by Django 5.1.15 on 2026-04-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_agent_challenge_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='openrouter_api_key_override_encrypted',
            field=models.TextField(blank=True, db_column='openrouter_api_key_override', default=''),
        ),
    ]
