# Generated by Django 5.0.4 on 2026-04-02 14:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_type', models.CharField(choices=[('in_app', 'In App'), ('slack', 'Slack'), ('email', 'Email')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_deletable', models.BooleanField(default=True)),
                ('slack_workspace_id', models.CharField(blank=True, max_length=255)),
                ('slack_bot_token', models.TextField(blank=True)),
                ('slack_webhook_url', models.URLField(blank=True)),
                ('email_provider', models.CharField(blank=True, max_length=20)),
                ('email_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_channels',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('agent_question', 'Agent Question'), ('agent_completed', 'Agent Completed'), ('plan_generated', 'Plan Generated'), ('pr_created', 'Pr Created'), ('pr_merged', 'Pr Merged'), ('review_completed', 'Review Completed'), ('review_approved', 'Review Approved'), ('review_changes', 'Review Changes'), ('fix_applied', 'Fix Applied'), ('ticket_assigned', 'Ticket Assigned'), ('mention', 'Mention'), ('invitation', 'Invitation')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True)),
                ('action_url', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('channels_sent', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='agents.agentrun')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
