# Generated by Django 5.0.4 on 2026-04-02 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('challenge', 'Challenge'), ('plan', 'Plan'), ('code', 'Code'), ('review', 'Review'), ('fix', 'Fix')], max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('waiting', 'Waiting'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=10)),
                ('auto_triggered', models.BooleanField(default=False)),
                ('total_input_tokens', models.IntegerField(default=0)),
                ('total_output_tokens', models.IntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('total_steps', models.IntegerField(default=0)),
                ('result_summary', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agent_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentRunStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('step_type', models.CharField(choices=[('context_retrieval', 'Context Retrieval'), ('analysis', 'Analysis'), ('question_gen', 'Question Gen'), ('plan_gen', 'Plan Gen'), ('code_gen', 'Code Gen'), ('code_review', 'Code Review'), ('review_analysis', 'Review Analysis'), ('fix_gen', 'Fix Gen'), ('refinement', 'Refinement')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('system_prompt', models.TextField(blank=True)),
                ('user_prompt', models.TextField(blank=True)),
                ('raw_response', models.TextField(blank=True)),
                ('parsed_result', models.JSONField(blank=True, default=dict)),
                ('model_used', models.CharField(default='claude-sonnet-4-20250514', max_length=100)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('is_success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agent_run_steps',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completeness_score', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('questions', models.JSONField(default=list)),
                ('is_approved', models.BooleanField(default=False)),
                ('requires_input', models.BooleanField(default=False)),
                ('relevant_files', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImplementationPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True)),
                ('estimated_complexity', models.CharField(blank=True, choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')], max_length=2)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'implementation_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('step_type', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('test', 'Test'), ('migration', 'Migration'), ('config', 'Config'), ('docs', 'Docs')], max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('files_to_modify', models.JSONField(default=list)),
                ('files_to_create', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'plan_steps',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ReviewFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=1000)),
                ('start_line', models.IntegerField(blank=True, null=True)),
                ('end_line', models.IntegerField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor'), ('suggestion', 'Suggestion')], max_length=10)),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('security', 'Security'), ('performance', 'Performance'), ('style', 'Style'), ('test', 'Test'), ('plan_drift', 'Plan Drift'), ('logic', 'Logic')], max_length=15)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('suggested_fix', models.TextField(blank=True)),
                ('fix_status', models.CharField(choices=[('open', 'Open'), ('fixed', 'Fixed'), ('wontfix', 'Wontfix'), ('ignored', 'Ignored')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'review_findings',
                'ordering': ['severity', 'file_path', 'start_line'],
            },
        ),
        migrations.CreateModel(
            name='ReviewResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True)),
                ('plan_conformity_score', models.IntegerField(blank=True, null=True)),
                ('total_findings', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('major_count', models.IntegerField(default=0)),
                ('minor_count', models.IntegerField(default=0)),
                ('suggestion_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'review_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
