# Generated by Django 5.0.4 on 2026-04-02 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_initial'),
        ('projects', '0001_initial'),
        ('scm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='triggered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentrunstep',
            name='agent_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agents.agentrun'),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='agent_run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='agents.agentrun'),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='projects.ticket'),
        ),
        migrations.AddField(
            model_name='implementationplan',
            name='agent_run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='agents.agentrun'),
        ),
        migrations.AddField(
            model_name='implementationplan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='implementationplan',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='projects.ticket'),
        ),
        migrations.AddField(
            model_name='planstep',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agents.implementationplan'),
        ),
        migrations.AddField(
            model_name='planstep',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scm.repository'),
        ),
        migrations.AddField(
            model_name='reviewfinding',
            name='fixed_by_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agents.agentrun'),
        ),
        migrations.AddField(
            model_name='reviewresult',
            name='agent_run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_result', to='agents.agentrun'),
        ),
        migrations.AddField(
            model_name='reviewresult',
            name='pull_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='scm.pullrequest'),
        ),
        migrations.AddField(
            model_name='reviewresult',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='projects.ticket'),
        ),
        migrations.AddField(
            model_name='reviewfinding',
            name='review_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='agents.reviewresult'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['ticket', 'agent_type'], name='agent_runs_ticket__fe3cce_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['status'], name='agent_runs_status_c2c587_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['created_at'], name='agent_runs_created_70e0e7_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrunstep',
            index=models.Index(fields=['agent_run', 'position'], name='agent_run_s_agent_r_977246_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysis',
            index=models.Index(fields=['ticket'], name='ai_analyses_ticket__31f166_idx'),
        ),
        migrations.AddIndex(
            model_name='implementationplan',
            index=models.Index(fields=['ticket'], name='implementat_ticket__9e94fd_idx'),
        ),
        migrations.AddIndex(
            model_name='planstep',
            index=models.Index(fields=['plan', 'position'], name='plan_steps_plan_id_c9d5b1_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewresult',
            index=models.Index(fields=['ticket'], name='review_resu_ticket__fe9fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewresult',
            index=models.Index(fields=['pull_request'], name='review_resu_pull_re_487b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewfinding',
            index=models.Index(fields=['review_result', 'severity'], name='review_find_review__07396b_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewfinding',
            index=models.Index(fields=['fix_status'], name='review_find_fix_sta_ae0c05_idx'),
        ),
    ]
