# Generated by Django 5.1.15 on 2026-04-03 14:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_initial'),
        ('projects', '0003_project_agent_challenge_instructions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('challenge', 'Challenge'), ('plan', 'Plan'), ('code', 'Code'), ('review', 'Review'), ('fix', 'Fix')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('llm_model', models.CharField(default='anthropic/claude-sonnet-4-20250514', max_length=200)),
                ('temperature', models.FloatField(default=0.3)),
                ('max_tokens', models.IntegerField(blank=True, null=True)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('trigger_on_ticket_created', models.BooleanField(default=False)),
                ('trigger_on_ticket_moved', models.BooleanField(default=False)),
                ('trigger_on_ticket_modified', models.BooleanField(default=False)),
                ('trigger_on_pr_created', models.BooleanField(default=False)),
                ('trigger_on_pr_merged', models.BooleanField(default=False)),
                ('requires_challenge_approved', models.BooleanField(default=False)),
                ('requires_plan_approved', models.BooleanField(default=False)),
                ('requires_pr_created', models.BooleanField(default=False)),
                ('requires_review_completed', models.BooleanField(default=False)),
                ('post_notify_assignee', models.BooleanField(default=True)),
                ('post_notify_creator', models.BooleanField(default=False)),
                ('challenge_auto_approve_threshold', models.IntegerField(blank=True, null=True)),
                ('fix_severity_filter', models.JSONField(blank=True, default=list)),
                ('fix_max_iterations', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_move_to_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.column')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_configs', to='projects.project')),
                ('trigger_move_source_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.column')),
                ('trigger_move_target_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.column')),
            ],
            options={
                'db_table': 'agent_configs',
                'unique_together': {('project', 'agent_type')},
            },
        ),
    ]
