# Generated by Django 5.1.15 on 2026-04-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agentconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='conversation_state',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
