# Generated by Django 5.0.4 on 2026-04-02 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=1000)),
                ('chunk_index', models.IntegerField()),
                ('chunk_content', models.TextField()),
                ('start_line', models.IntegerField()),
                ('end_line', models.IntegerField()),
                ('language', models.CharField(blank=True, max_length=50)),
                ('commit_sha', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'code_embeddings',
            },
        ),
        migrations.CreateModel(
            name='ProjectRepository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_branch_override', models.CharField(blank=True, max_length=255)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_repositories',
            },
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=50)),
                ('external_url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('branch_name', models.CharField(max_length=255)),
                ('target_branch', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('merged', 'Merged'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('files_changed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pull_requests',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=500)),
                ('external_id', models.CharField(max_length=255)),
                ('clone_url', models.URLField(max_length=500)),
                ('default_branch', models.CharField(default='main', max_length=255)),
                ('html_url', models.URLField(blank=True, max_length=500)),
                ('indexing_status', models.CharField(choices=[('pending', 'Pending'), ('indexing', 'Indexing'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('last_indexed_commit', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'repositories',
            },
        ),
        migrations.CreateModel(
            name='SCMConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_type', models.CharField(choices=[('github', 'Github'), ('bitbucket', 'Bitbucket'), ('gitlab', 'Gitlab')], max_length=10)),
                ('installation_id', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('external_org_name', models.CharField(blank=True, max_length=255)),
                ('external_org_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scm_connections',
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('github', 'Github'), ('bitbucket', 'Bitbucket'), ('gitlab', 'Gitlab'), ('stripe', 'Stripe'), ('slack', 'Slack')], max_length=10)),
                ('event_type', models.CharField(max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('headers', models.JSONField(default=dict)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='received', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'webhook_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
