# Generated by Django 5.0.4 on 2026-04-02 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        ('projects', '0002_initial'),
        ('scm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrepository',
            name='linked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectrepository',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_repositories', to='projects.project'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='projects.ticket'),
        ),
        migrations.AddField(
            model_name='repository',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repository',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='scm.repository'),
        ),
        migrations.AddField(
            model_name='projectrepository',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='scm.repository'),
        ),
        migrations.AddField(
            model_name='codeembedding',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='scm.repository'),
        ),
        migrations.AddField(
            model_name='scmconnection',
            name='connected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scmconnection',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scm_connections', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='repository',
            name='scm_connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='scm.scmconnection'),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['ticket'], name='pull_reques_ticket__ba1a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['repository'], name='pull_reques_reposit_13d28b_idx'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['status'], name='pull_reques_status_19c420_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectrepository',
            unique_together={('project', 'repository')},
        ),
        migrations.AddIndex(
            model_name='codeembedding',
            index=models.Index(fields=['repository', 'file_path'], name='code_embedd_reposit_a2a739_idx'),
        ),
        migrations.AddIndex(
            model_name='scmconnection',
            index=models.Index(fields=['organization', 'provider_type'], name='scm_connect_organiz_76f064_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['organization'], name='repositorie_organiz_d54ae1_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['indexing_status'], name='repositorie_indexin_f07568_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('organization', 'scm_connection', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['source', 'event_type'], name='webhook_eve_source_683499_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['status'], name='webhook_eve_status_330e1f_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['created_at'], name='webhook_eve_created_8fa52f_idx'),
        ),
    ]
