# Generated by Django 5.1.15 on 2026-04-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrepository',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
