# Generated by Django 5.1.15 on 2026-04-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_notification_channel',
            field=models.CharField(choices=[('in_app', 'In-App'), ('slack', 'Slack'), ('email', 'Email')], default='in_app', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.CharField(default='Europe/Paris', max_length=50),
        ),
    ]
