# Generated by Django 5.1.15 on 2026-04-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_default_notification_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='openrouter_api_key_encrypted',
            field=models.TextField(blank=True, db_column='openrouter_api_key', default=''),
        ),
    ]
